spring.application.name=Taskmanagement
spring.data.mongodb.uri=mongodb://localhost:27017/task
server.port=8082

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
